<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PTSLO3OM" failures="2" tests="4" name="Test" time="150.701" errors="0" timestamp="2024-06-03T17:32:56 IST">
  <testcase classname="SeleniumProj.AutomateFramework2.OrderHistory" name="viewOrders" time="16.849"/>
  <testcase classname="SeleniumProj.AutomateFramework2.OrderHistory" name="ErrorValidation2" time="9.667">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully#] but found [Login Successfully]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully#] but found [Login Successfully]
at SeleniumProj.AutomateFramework2.OrderHistory.ErrorValidation2(OrderHistory.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ErrorValidation2 -->
  <testcase classname="SeleniumProj.AutomateFramework2.SubmitOrder" name="submitorder" time="16.346"/>
  <testcase classname="SeleniumProj.AutomateFramework2.SubmitOrder" name="ErrorValidation" time="26.058">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully.] but found [Login Successfully]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully.] but found [Login Successfully]
at SeleniumProj.AutomateFramework2.SubmitOrder.ErrorValidation(SubmitOrder.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ErrorValidation -->
</testsuite> <!-- Test -->
